### ISSUE TITLE
adjust height of buttons

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#26]
These are 50px height in the mock up, can I see what that looks like? Also, would like arrow to be the same size as supplied. 
<img width="121" alt="screen shot 2016-06-21 at 6 47 06 pm" src="https://cloud.githubusercontent.com/assets/20047847/16250045/ec524b62-37df-11e6-8f89-258a6aaee01a.png">
<img width="126" alt="screen shot 2016-06-21 at 6 47 01 pm" src="https://cloud.githubusercontent.com/assets/20047847/16250046/ec54c25c-37df-11e6-8c69-50419639c791.png">
<img width="269" alt="screen shot 2016-06-21 at 6 46 27 pm" src="https://cloud.githubusercontent.com/assets/20047847/16250043/ec512660-37df-11e6-8ebe-220aecefad12.png">
<img width="622" alt="screen shot 2016-06-21 at 6 46 07 pm" src="https://cloud.githubusercontent.com/assets/20047847/16250044/ec51be2c-37df-11e6-8503-246169629791.png">

**Comment by 808loud** [comment]
All buttons are exactly 50px tall (16px font-size with 17px padding on top and bottom). 

SVG icons are all 50px by 50px, thanks to the standardized dimensions of every SVG icon (16px by 16px).

Behance and LinkedIn buttons are set to a minimum-width of 50px so that they don't look weird, and so that they don't "pop" once the font-awesome icon library finishes loading during initial page load.
