### ISSUE TITLE
Fixed button position in modal

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#30]
Can the X be static like the nav bar?
<img width="325" alt="screen shot 2016-06-21 at 6 56 50 pm" src="https://cloud.githubusercontent.com/assets/20047847/16250208/279bc6c0-37e1-11e6-8f7a-7aae58c169a3.png">

**Comment by 808loud** [comment]
In order to achieve the fixed positioning of an element inside a modal window, I needed to remove the transform property from the modal window. There should be little-to-no noticeable difference to the end user, but I wanted to note that according this [this comment](https://github.com/twbs/bootstrap/issues/15856#issuecomment-75314084) from a bootstrap core team member, removing the transform makes the modal window slightly less performant.

**Comment by charlydsgn** [comment]
Hmm, it would be nice to have the "X" fixed at the top to be consistent with all the other header nav functionality. I'd say go for it.

**Comment by 808loud** [comment]
Shouldn't have any noticable impact. Pushed to master.
