### ISSUE TITLE
Remaining issues

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#68]
As mentioned in our conversation, the live site is just how I like it with exception to the following. 
1. Line spacing of grey header in mobile only. The dashes and spaces are good as is. **Make sure when line spacing gets adjusted for the headers that it doesn't affect anything else. See below. 
2. Paralax does not work in Firefox. 
3. Margin for the quotes ( you fixed this in the develop site ). For the rest of the site I'm open to the wider margins or outer white space you established in develop so long as you can assure the kind of centering with the X/Arrow/Artwork I currently have for the modal windows in the live site. 

Try to visually compare the two as best you can and adjust accordingly. Thanks for sticking with this, I know it's a pain but one way to look at it is that this will make you stronger for when you have to work with other people like me (and worse) down the road. I had to work under a few woozies in my day so I can sort of relate.

<img width="337" alt="screen shot 2016-06-27 at 11 52 28 pm" src="https://cloud.githubusercontent.com/assets/20047847/16404125/aaeed8ca-3cc1-11e6-907a-ab66ae2dbebb.png">

**Comment by 808loud** [comment]
These should all be fixed on develop and master, so I am closing. 

In order to fix line spacing, I implemented a new line-height (the CSS equivalent on line spacing) on headings. However, in CSS, extra padding is added on the top of lines as well as the bottom. This is just how the spec is written, and something that web devs have to deal with. I have made the proper adjustments to padding (ex: the hero heading text) and positioning (ex: the em dashes) to account for this.

Because of this, the new files will not be 100% pixel perfect to what you have on the live site. But again, this is simply how CSS is written. If you want line spacing, along with it you get some padding on the top of text (and below, obviously as well... which is where we want it). So with the tweaks I've made, we're at about 99.9995% pixel perfect to what you have on the live site. 

I made sure that the em dashes under the left headings, and the line spacing and margins on the hero heading text were 100% pixel perfect, because I have the opportunity to do so in those areas, and because I know those area areas of special interest to your design. 

P.S. The live site's hero image was being allowed to grow too large because of the increased line spacing (done to make it look nice when wrapping to two lines). So I tweaked the code on my end to make the hero image exactly 424px tall as per the style guide.
